sudo: false
language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: npm release
      node_js: node
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email:
          secure: "hu6mnnx+Zf+w0q8upRKKISu/tBiwouNt4Pk3SbncpOCbJ0rOOgVMHnJrPD0QdnNfPc32jLloJj0Bh6sa7cR18k/jx4zVMv7n8tcPpQELzezE8liu09PWjqntwO7Z5na+HJx0SdlFa708XyzIEX4x0gm3q438mGyiGdMC1Vn/Mict8A7c+BpnwzmPP9mZJL5ZHljZnweHj66ERU/gLHaRlNym13RWGu+C4zkv7i8HBhsBrmfecsGhsYzObfauWbYm8AOgsddAwZAP8/PsnSfR/Uc5iyco7KEAjLw3p/P/bntLOuferFx4C3dwJP4bKqZHSNkj/oKkANRU4yj+Ae6gfLjOl/CG7DiDk4NS7xWvJvLOldOXIQpFWXUbDr2B4SVRu2axBh6v5pkcoLvbYLQS8ZSsZQF6pO8dRApQ8LeBIjLyaHLTmiRPzN1JrApFtlNX7FcJIz2Gese2gJSKaf7cFwm9SVjxutyxIs2daXIiqaapxozm3Vt6RN+ccq1cF+TFkft+RbH+XWV9y8ERuJAQZTg2UsdE8uSNYjnVtSB8AUE68ifZXBXtUn+mHD+eijLJzaPoH2Ka7mBYxwbUolYKt/JgWJ++BgZbUJ+WS6ervPd+AEUzrWFONyD4zguO18DcJW+v/6bymuXQj3ks+WjR59S71qa0Q/x3zOvS+9uNt04="
        api_key: # b032
          secure: "e5V4RifNgYDKc6k2dIcKiFPf3PqL1XyXqLbuUcE0+7W6hTZL21f7+lQJzOM2jdDlu1EumqKD/LBWBsMqMFyzPTPIwQcA/1Ha5uJ9jvTIXGKCV9EZy3wDta3M1vSVMIWzK62bUExs0rIMMiDzKV+z56/U2vCjNGRBIZoip8sWQ4Ya32soiWvttozGx7Ck9SP1SOF60CZ9tdjEjziTeA3L1P91XOv4zd9WDLP5AFBHeICQ1A7+3iq+/4gTvo1WkQuS6zWA8QVfLcGr/mhvVhyw5oetgLOA0UT60gz31tDJq4AlZH3XuUc87upKqiZxLQHB1h2xkDnWjgwbnePHSf5q4mwQUhuD1AeoQGDtwKVVpKzvEXueEEawpgm/yz1csRWvWCk9+GlKeAzkb0qKTYDudIWLDriw1tokFOujkiL9KHJAC3q+VXWvtindO+kbi8I1PsESymVJ9CM9ENO0quzOBoMHdJwIcO/jECixJSkxCqlNWCnwwXdvZZmwliWu5C+hAnsHLstwBDmO0pa23JaqgQrcG1ucckGoVyB0IXPoM51v/fPKXc9TxxGdPOwN/T2cPpwqPRe54WJzOmAGc/JRTZK+Igz8I5BWM0Uoeysjn/e6fHdPv6smju2FB0sdMEoZuUxncRAjmr23SffuE2Cnmz5vmGMLTkHQoxA8UQIyYbo="
        on:
          tags: true
          node: node
